config/routes.rb
Rails.application.routes.draw do
  devise_for :logins

  resources :home, only: :index
  root 'home#index'
  resources :voyages
  
  resources :cargos
  resources :locations
  resources :legs
  resources :itineraries 

  resources :itinerary_bookings, only: [] do
    collection do
      post :generate_itinerary
    end
  end

end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  validates :start_location_id, presence: true
  validates :end_location_id,   presence: true
  validates :arrival_time,      presence: true
  validates :layover_minutes,   presence: true
  # validates :cargo,             presence: true

  belongs_to :start_location,   class_name: 'Location'
  belongs_to :end_location,     class_name: 'Location'
  has_many   :legs,             dependent: :destroy
  belongs_to :cargo

  def add_leg(leg)
    legs.create(
      load_location_id:      leg.load_location_id,
      load_time:             leg.load_time,
      unload_location_id:    leg.unload_location_id,
      unload_time:           leg.unload_time
    )
  end

  def hops
    legs.count
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < RestCmdsController
  # see RestCmdsController for actions:  :index :show :new :edit :create :update :destroy

  private

    def controlled_klass
      Itinerary
    end

    def controlled_klass_presenter
      ItineraryPresenter
    end

    def controlled_klass_index_url
      itineraries_url
    end

    def permit_params
      params.require(:itinerary).permit(:start_location_id, :end_location_id, :arrival_time, :layover_minutes)
    end

    def search_criteria
      criteria = Criteria.new
      q = params[:q]
      if q
        # code = (q || '').strip.to_i
        criteria.where(start_location_id: start_location_id)
      end
      criteria
    end
end

app/views/itineraries/_form.html.erb
<%= form_for(prez.target) do |f| %>
  <% if prez.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prez.errors.count, "error") %> prohibited this itinerary from being saved:</h2>

      <ul>
      <% prez.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>    
      
    </div>
  <% end %>
       
  <fieldset>    
    <div> 
       <%= f.label :start_location_id %>
       <%= f.text_field :start_location_id %>
    </div>
    <div> 
       <%= f.label :start_location_id %>
       <%= f.text_field :start_location_id %>
    </div>
    <div> 
       <%= f.label :arrival_time %>
       <%= f.text_field :arrival_time %>
    </div>
    <div> 
       <%= f.label :layover_minutes %>
       <%= f.text_field :layover_minutes %>
    </div>

  </fieldset>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/itineraries/edit.html.erb
<h1>Editing Itinerary</h1>

<%= render 'form' %>

<%= prez.link_to_show %> |
<%= prez.link_to_index('Back') %>

app/views/itineraries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Itineraries</h1>

<div id="search">
  <%= form_tag itineraries_path, method: :get do %>
    <%= text_field_tag( 'q', nil, class: "text", type: 'text', title:"Search", 
                       value: @q,  placeholder: "Code"  ) %> 
    <br/>
    <input type="submit" value="Find Itinerary Start ID", autofocus="true" /> 
  <%- end -%>
</div>


<table>
  <thead>
    <tr>
      <% prez.titles.each do |title| %>
        <th><%= title %></th>
      <% end  %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% prez.each do |single_prez| %>
      <tr>            
        <% single_prez.values.each do | value | %>
          <td><%= exhibit(value, self) %> </td> 
        <% end %>
        <td><%= single_prez.link_to_show %></td>
        <td><%= single_prez.link_to_edit %></td>
        <td><%= single_prez.link_to_destroy %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= prez.link_to_new %>

app/views/itineraries/new.html.erb
<h1>New Itinerary</h1>

<%= render 'form' %>

<%= link_to 'Back', itineraries_path %>

app/views/itineraries/show.html.erb
<h1>Itinerary</h1>
<p id="notice"><%= notice %></p> 
<%= exhibit(prez.target, self) %>

<br/>
<br/>
<%= prez.link_to_cargo %>
                                                                      
<h3> Legs</h3>  
<% prez.legs.each do |leg|   %>  
  <%= exhibit(leg, self)   %>  <br>
<% end %>
<br>                                                                                           