config/routes.rb
Rails.application.routes.draw do
  devise_for :logins

  resources :home, only: :index
  root 'home#index'
  resources :voyages
  
  resources :cargos
  resources :locations
  resources :legs
  resources :itineraries 

  resources :itinerary_bookings, only: [] do
    collection do
      post :generate_itinerary
    end
  end

end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
  validates :origin_id,           presence: true
  validates :destination_id,      presence: true
  validates :arrival_deadline_on, presence: true

  belongs_to :origin,      class_name: 'Location'
  belongs_to :destination, class_name: 'Location'

  has_one :itinerary

  def describe
    "#{origin.code} => #{destination.code} by #{arrival_deadline_on}"
  end
end

app/controllers/cargos_controller.rb
class CargosController < RestCmdsController
  # see RestCmdsController for actions:  :index :show :new :edit :create :update :destroy

  private

    def controlled_klass
      Cargo
    end

    def controlled_klass_presenter
      CargoPresenter
    end

    def controlled_klass_index_url
      cargos_url
    end

    def permit_params
      params.require(:cargo).permit(:origin_id, :destination_id, :arrival_deadline_on)
    end

    def search_criteria
      criteria = Criteria.new
      q = params[:q]
      if q
        destination_id = (q || '').strip.to_i
        criteria.where(destination_id: destination_id)
      end
      criteria
    end
end

app/views/cargos/_form.html.erb
<%= form_for(prez.target) do |f| %>
  <% if prez.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prez.errors.count, "error") %> prohibited this cargo from being saved:</h2>

      <ul>
      <% prez.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>    
      
    </div>
  <% end %>
       
  <fieldset>
    
    <div> 
       <%= f.label :origin_id, "Origin" %>
       <%= f.select 'origin_id',  prez.location_options %>
    </div>
    <div> 
       <%= f.label :destination_id, "Destination" %> 
       <%= f.select 'destination_id', prez.location_options  %>
    </div>

    <p><%= f.label :arrival_deadline_on %> 
       <%= f.date_select  :arrival_deadline_on  %>
    </p>
  </fieldset>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cargos/edit.html.erb
<h1>Editing Cargo</h1>

<%= render 'form' %>

<%= prez.link_to_show %> |
<%= prez.link_to_index('Back') %>

app/views/cargos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cargos</h1>

<div id="search">
  <%= form_tag cargos_path, method: :get do %>
    <%= text_field_tag( 'q', nil, class: "text", type: 'text', title:"Search", 
                       value: @q,  placeholder: "Destination_id"  ) %> 
    <br/>
    <input type="submit" value="Find Destination", autofocus="true" /> 
  <%- end -%>
</div>


<table>
  <thead>
    <tr>
      <% prez.titles.each do |title| %>
        <th><%= title %></th>
      <% end  %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% prez.each do |cargo_prez| %>
      <tr>            
        <% cargo_prez.values.each do | value | %>
          <td><%= exhibit(value, self) %> </td> 
        <% end %>
        <td><%= cargo_prez.link_to_show %></td>
        <td><%= cargo_prez.link_to_edit %></td>
        <td><%= cargo_prez.link_to_destroy %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= prez.link_to_new %>

app/views/cargos/new.html.erb
<h1>New Cargo</h1>

<%= render 'form' %>

<%= link_to 'Back', cargos_path %>

app/views/cargos/show.html.erb
<h1>Cargo</h1>
<p id="notice"><%= notice %></p>

<%= exhibit(prez.target, self) %>

<br/>
<br/>
<%= prez.link_to_edit %> |
<%= prez.link_to_index('Back') %>

<%= button_to( "Generate Itinerary", generate_itinerary_itinerary_bookings_path(cargo_id: prez.target.id) ) %>

<p> <%= prez.link_to_itinerary %></p>
<p> TODO: Button to finalize booking</p>
<%= image_tag "Cargo", width: '100', height: '100' %>