config/routes.rb
Rails.application.routes.draw do
  devise_for :logins

  resources :home, only: :index
  root 'home#index'
  resources :voyages
  
  resources :cargos
  resources :locations
  resources :legs
  resources :itineraries 

  resources :itinerary_bookings, only: [] do
    collection do
      post :generate_itinerary
    end
  end

end

app/models/voyage.rb
class Voyage < ActiveRecord::Base
  validates :home_port_id, presence: true
  after_create :create_schedule

  has_one    :schedule
  belongs_to :home_port, class_name: 'Location'

  delegate :add_movement, to: :schedule

  def available?
    ValidVoyageRule.new(self).satisfied?
  end

  def why_available
    auditor = Auditor.new
    ValidVoyageRule.new(self).satisfied?(auditor)
    auditor.explain
  end

  delegate :hops, to: :schedule

  def last_location
    schedule.carrier_movements.last.arrival_location
  end

  def last_arrival_at
    schedule.carrier_movements.last.arrival_at
  end
end

app/controllers/voyages_controller.rb
class VoyagesController < RestCmdsController
  # see RestCmdsController for actions:  :index :show :new :edit :create :update :destroy

  private

    def controlled_klass
      Voyage
    end

    def controlled_klass_presenter
      VoyagePresenter
    end

    def controlled_klass_index_url
      voyages_url
    end

    def permit_params
      params.require(:voyage).permit(:home_port_id)
    end

    def search_criteria
      criteria = Criteria.new
      q = params[:q]
      if q
        home_port_id = (q || '').strip.to_i
        criteria.where(home_port_id: home_port_id)
      end
      criteria
    end
end

app/views/voyages/_form.html.erb
<%= form_for(prez.target) do |f| %>
  <% if prez.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prez.errors.count, "error") %> prohibited this voyage from being saved:</h2>

      <ul>
      <% prez.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>    
      
    </div>
  <% end %>
       
  <fieldset>
    
    <div> 
       <%= f.label :home_port_id, "HomePort" %>
       <%= f.select 'home_port_id',  prez.location_options %>
    </div>
  </fieldset>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/voyages/edit.html.erb
<h1>Editing Voyage</h1>

<%= render 'form' %>

<%= prez.link_to_show %> |
<%= prez.link_to_index('Back') %>

app/views/voyages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Voyages</h1>

<div id="search">
  <%= form_tag voyages_path, method: :get do %>
    <%= text_field_tag( 'q', nil, class: "text", type: 'text', title:"Search", 
                       value: @q,  placeholder: "Homep Port ID"  ) %> 
    <br/>
    <input type="submit" value="Find Home Port", autofocus="true" /> 
  <%- end -%>
</div>


<table>
  <thead>
    <tr>
      <% prez.titles.each do |title| %>
        <th><%= title %></th>
      <% end  %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% prez.each do |voyage_prez| %>
      <tr>            
        <% voyage_prez.values.each do | value | %>
          <td><%= exhibit(value, self) %> </td> 
        <% end %>
        <td><%= voyage_prez.link_to_show %></td>
        <td><%= voyage_prez.link_to_edit %></td>
        <td><%= voyage_prez.link_to_destroy %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= prez.link_to_new %>

app/views/voyages/new.html.erb
<h1>New Voyage</h1>

<%= render 'form' %>

<%= link_to 'Back', voyages_path %>

app/views/voyages/show.html.erb
<h1>Voyage</h1>
<p id="notice"><%= notice %></p>

<%= exhibit(prez.target, self) %>
<div> Available: <%= prez.available %>: <%= prez.why_available %></div>
<br/>
<br/>
<%= prez.link_to_edit %> |
<%= prez.link_to_index('Back') %>

<h3> Carrier Movements</h3>  
<% prez.carrier_movements.each do |carrier_movement|   %>  
  <%= exhibit(carrier_movement, self)   %>  <br>
<% end %>
<br>
<%= image_tag "CargoShip", width: '150', height: '100' %>