config/routes.rb
Rails.application.routes.draw do
  devise_for :logins

  resources :home, only: :index
  root 'home#index'
  resources :voyages
  
  resources :cargos
  resources :locations
  resources :legs
  resources :itineraries 

  resources :itinerary_bookings, only: [] do
    collection do
      post :generate_itinerary
    end
  end

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to("Cargos",    cargos_url) %> </li>
<li><%= link_to("Locations", locations_url) %></li>
<li><%= link_to("Voyages",   voyages_url) %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tvd" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tvd" %>">
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>